boostcampwm-2022/web24-Asnity

- server/apps/api/src/main.ts
- server/dao/repository/user.repository.ts
- server/dao/schemas/channel.schema.ts
- server/dao/schemas/chat.schema.ts
- server/dao/schemas/user.schema.ts
- server/tsconfig.json
- server/utils/def.ts
- #9 
- user document 생성시 save -> create 수정
- repository type 관련 파일 위치 변경
> refactor: user repo create 수정 #9

- server/apps/api/src/user/auth/dto/auth.dto.ts
- server/apps/api/src/user/auth/dto/index.ts
- #6 
- #7 
SingInDto, SignUpDto 생성
- 포맷이 올바르진 확인하기 위한 검증
Closes #6 
Closes #7
> [SERVER] #6, #7 로그인 포맷, 회원가입 포맷 생성

- client/tailwind.config.js
> [CLIENT] tailwind config theme 상수 값, 프로퍼티 이름 수정

- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.module.ts
- server/apps/api/src/user/user.service.ts
- server/dao/repository/user.repository.ts
user.repository.ts 내부 클래스 명 수정
> refactor: usersRepository -> userRepository 클래스 명 수정

- server/apps/api/src/auth/auth.controller.ts
- server/apps/api/src/auth/auth.service.ts
- server/dao/repository/user.repository.ts
- #10 
- #13 
로그인 기능 구현
- user.repository에 findOne 함수 생성 (조건에 맞는 것을 DB에서 찾아서 반환)
- 로그인 로직 구현
- DB에 아이디가 없으면 예외처리
- 비밀번호가 일치하지 않으면 예외처리
>**To-do : 로그인 성공 시, accessToken, refreshToken 발행**
- Closes #10
> feat: 로그인 기능 구현

- client/.eslintrc
- client/src/App.tsx
- client/src/pages/DM/index.tsx
- client/src/pages/Friends/index.tsx
- client/src/pages/Home/index.tsx
- #47 
Closes #47
* * *
- 기존: DM 페이지와 커뮤니티 페이지는 별개의 페이지로 Gnb를 공유하지 않았음
- 변경 후: DM 페이지와 커뮤니티 페이지를 `/` 경로 아래에 두어 Gnb를 공유하게 됨
> [CLIENT] 공통 레이아웃 적용을 위한 라우팅 구조 수정

- client/src/features/CommunityNav/index.tsx
- client/src/features/DmNav/index.tsx
- client/src/features/Gnb/index.tsx
- client/src/features/Sidebar/index.tsx
- client/src/pages/DM/index.tsx
- client/src/pages/DMRoom/index.tsx
- client/src/pages/Friends/index.tsx
- client/src/pages/Home/index.tsx
- client/tailwind.config.js
> [CLIENT/FEAT] `Home` 페이지 레이아웃

- server/apps/api/src/user/dto/follower.dto.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.service.ts
- yarn.lock
- #21 
- #60 
- #20 
- #50 
- follower 정보와 following 정보를 전달하는 controller, service 작성
- refactoring : follow, unfollow 의 service layer에서 동일 함수로 toggle 방식으로 추가 삭제되도록 변경
> [Feature/followers] follower, follow 정보 요청 시 데이터 전달

- client/config/webpack.common.ts
- client/package.json
- client/src/common/components/Button/index.tsx
- client/src/common/components/SuccessMessage/index.tsx
- client/src/common/components/TextButton/index.tsx
- client/src/constants/url.ts
- client/src/index.tsx
- client/src/mocks/handlers/Auth.js
- client/src/mocks/handlers/index.js
- client/src/pages/SignUp/index.tsx
- client/tsconfig.json
- yarn.lock
- #37 
- 회원가입 기능 추가
- SignUp페이지 리팩토링 필요
> [Client] 회원가입 요청

- server/apps/api/src/auth/auth.controller.ts
- server/apps/api/src/auth/auth.service.ts
- server/apps/api/src/auth/dto/auth.dto.ts
- server/apps/api/src/main.ts
- server/apps/api/src/user/dto/create-user.dto.ts
- server/dao/repository/user.repository.ts
- server/dao/schemas/user.schema.ts
- server/utils/def.ts
- #이슈번호
#6 
#7 
>**문제사항 및 해결**
- 회원가입 시, user계정에 provider를 제공하지 않음 -> asnity 자체 회원가입 시, 'asnity'를 user에 추가하고 DB에 넣어줌
- class-validator가 적용되지 않음 -> useGlobalPipes를 main에 설정해줘서 적용되게 수정함
- 최소 8자 이상을 Min(8)로 했었는데 제대로 동작하지 않음 -> MinLength(8)로 수정
> [Fix/validation] validation 버그 수정

- server/apps/api/src/user/dto/user-basic-info.dto.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.service.ts
- server/dao/repository/user.repository.ts
- #22 
- 사용자 사용자 검색 시 primary id가 아닌 로그인 id 또는 nickname으로 검색하도록 수정
> [fix: 특정 사용자 정보 요청] 

- server/apps/api/src/user/dto/modify-user.dto.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.service.ts
- #75 
- 사용자 정보 수정 요청 시 사용자 정보 변경
- 변경가능한 정보 : password,
> [Feature/modify user info]

- server/.gitignore
- server/__mock__/user.mock.ts
- server/apps/api/src/user/user.service.spec.ts
- server/apps/api/src/user/user.service.ts
- server/apps/api/test/user.service.spec.ts
- server/package.json
- server/tsconfig.json
- no issue
- server user.service unit test
- user.service test 8개 수행
- Test Coverage 약 92%
> [Server/Test] User Service Layer에 대한 Unit test

- .github/workflows/client.yml
main 브랜치로 PR 병합되었을 때,
client/** 에 변경사항이 발생하면
빌드 - S3 배포 - Cloudfront 캐시무효화를 수행하는 GitHub Action 워크플로우를 작성합니다.
> [CLIENT] CI/CD Workflow 작성

- package.json
- server/apps/api/src/api.module.ts
- server/apps/api/src/main.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.service.ts
- server/apps/webhook.interceptor.ts
- server/package.json
- yarn.lock
배포 서버 에러 발생 시 slack bot message
> [Server/Feature] error bot

- server/apps/api/src/auth/dto/index.ts
- server/apps/api/src/auth/dto/sign-in.dto.ts
- server/apps/api/src/auth/dto/sign-up.dto.ts
- 리펙토링
- auth.dto.ts -> sign-in.dto.ts, sing-out.dto.ts 로 분할
- 분할 이유: 나중에 수정할 일 생길 때 파일명만 보고 찾기가 쉬워짐
채널 구현하기에 앞서 auth를 리펙토링 해보았습니다
> [Server/auth] refactor: auth.dto.ts를 분할

- server/__mock__/community.mock.ts
- server/apps/api/src/api.module.ts
- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/community/community.module.ts
- server/apps/api/src/community/community.service.ts
- server/apps/api/src/community/dto/create-community.dto.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.module.ts
- server/apps/api/test/community.service.spec.ts
- server/dao/repository/community.repository.ts
- server/dao/schemas/community.schema.ts
- #86 
- 커뮤니티 생성 후 정보 return 
- create community service layer unit test
> [Server/Feature] create community

- client/src/apis/auth.ts
- client/src/hooks/useSignInMutation.ts
- client/src/pages/SignIn/index.tsx
- client/src/queryKeyCreator.ts
> [CLIENT] 로그인 페이지 리팩토링

- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/community/community.service.ts
- server/apps/api/src/community/dto/modify-community.dto.ts
- server/dao/repository/community.repository.ts
- #96 
- 커뮤니티 정보 수정 api 구현
- 매니저일시에만 수정 가능
- 정상 동작
- 커뮤니티 _id 검증
- 매니저 권한 확인
- 매니저 _id 검증
> [Server/Feature] modify community

- client/src/components/AuthInput/index.tsx
- #117 
AuthInput에 전달되는 ref props로 인해 발생하는 React Warning을 해결합니다.
> [CLIENT] AuthInput ref Warning 해결

- client/src/mocks/handlers/Auth.js
mock 데이터가 객체로 래핑되어 있어서 제대로 전달되지 않는 문제 있었음. mock 데이터에서 래핑 벗겨주는 것으로 해결
> [CLIENT] `UserProfile`에 mock 데이터 제대로 렌더링 되지 않는 문제 해결

- client/src/components/FollowingUserItem/index.tsx
- client/src/components/UserItem/index.tsx
- client/src/index.css
- client/src/layouts/Followers/index.tsx
- client/src/layouts/Followings/index.tsx
- client/src/layouts/UserSearch/index.tsx
- client/src/pages/Friends/index.tsx
- client/src/pages/Home/index.tsx
- client/src/pages/UnAuthorizedLayer/index.tsx
- client/src/utils/axios.ts
> [CLIENT] Home 레이아웃 관련 스타일 선언

- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channel.module.ts
- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/dto/create-channel.dto.ts
- server/apps/api/src/channel/dto/index.ts
- server/apps/api/src/community/community.module.ts
- server/dao/repository/channel.repository.ts
- server/dao/schemas/channel.schema.ts
- server/utils/addObjectForm.ts
- #111 
채널 생성 로직 구현
- channel document 생성하는 함수를 구현
- `create`
- `POST(/api/channel/)`
- `UseGuards(JwtAccessGuard)`
- 채널 생성하는 로직을channel service에 작성
- 제대로 생성되지 않으면 에러처리
- 채널 생성 성공시
- 채널 생성 중 오류 발생
> [Server/channel] 채널 생성

- client/package.json
- client/src/apis/dm.ts
- client/src/components/FollowingUserItem/index.tsx
- client/src/components/UserItem/index.tsx
- client/src/components/UserList/index.tsx
- client/src/components/UserProfile/index.tsx
- client/src/hooks/useDirectMessagesQuery.ts
- client/src/layouts/DmNav/index.tsx
- client/src/layouts/Followers/index.tsx
- client/src/layouts/Followings/index.tsx
- client/src/layouts/UserSearch/index.tsx
- client/src/mocks/data/users.js
- client/src/mocks/handlers/DM.js
- client/src/mocks/handlers/User.js
- client/src/mocks/handlers/index.js
- client/src/queryKeyCreator.ts
- client/src/stores/tokenStore.ts
- client/src/types/apis/process.d.ts
- client/tsconfig.json
- yarn.lock
- #125 
DM 페이지로 갈 수 있는 `DMNav` 작성
> [CLIENT] DM 목록 보여주는 `DMNav` 작성

- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/community/community.module.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/user.module.ts
- server/apps/api/src/user/users.controller.ts
- #22 
- #115 
- Frontend API 요청사항 반영했으니 확인 부탁드립니다.
- 특정 사용자 확인 시 `Get user -> Get users&search={name}`
> [Server/Refactor] 복수형 API 수정

- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/community/community.service.ts
- server/apps/api/src/community/dto/request-user-about-community.dto.ts
- #141 
- `@Get /api/community/:id/participants`
-  각 사용자 정보는 userBasicInfo
- verifyCommunity -> getCommunity function name revise
- 정상 동작
- 자신이 속하지 않은 커뮤니티 요청 시 또는 올바르지 않은 커뮤니티 _id로 요청시
> [Server/Feature] 요청하는 커뮤니티의 사용자들 정보 가져오기

- client/src/App.tsx
- client/src/apis/community.ts
- client/src/components/Avatar/index.tsx
- client/src/components/Input/index.tsx
- client/src/components/Modals/CreateCommunityModal/index.tsx
- client/src/hooks/community.ts
- client/src/layouts/CommunityNav/index.tsx
- client/src/layouts/Gnb/index.tsx
- client/src/mocks/data/communities.js
- client/src/mocks/handlers/Community.js
- client/src/mocks/utils/createContext.js
- client/src/mocks/utils/rand.js
- client/src/pages/Channel/index.tsx
- client/src/pages/Community/index.tsx
- client/src/queryKeyCreator.ts
- #149 
Gnb와 Channel Route를 추가하였습니다.
- 커뮤니티 입장시 디폴트 채널이 생성되긴 하지만, 그 채널에 바로 입장하는건 아니기 때문에 디폴트로 보여줘야 할 페이지가 필요하고, 이를 위해 `/communities/:communityId`에 해당하는 페이지가 필요해졌습니다.
- 아래 이미지처럼 `height` 사이즈가 작으면 이미지가 납작해져서 h-full 추가했습니다.  
- **첫 번째 사진이 Fix 이후입니다.**
- Gnb 툴팁, 우클릭시 컨텍스트 메뉴는 아직 추가하지 않음.
> [CLIENT] Gnb와 Channel Route 추가

- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channel.module.ts
- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/dto/channel-basic-info.dto.ts
- server/apps/api/src/channel/dto/index.ts
- server/apps/api/src/channel/dto/modify-channel.dto.ts
- server/apps/api/src/community/community.module.ts
- server/apps/api/src/community/community.service.ts
- server/apps/api/src/community/dto/community-basic-info.dto.ts
- server/dao/repository/channel.repository.ts
이전에 PR 보냈던거 머지가 안되는 이슈 발생으로 PR 다시 보냄
- #139
> [Server/Feature] Re: 현재 사용자가 속한 커뮤니티 및 채널들의 기본 정보 전달

- server/apps/api/src/channel/channel.service.ts
- server/dao/repository/channel.repository.ts
- #123 
- 비공개 채널일 경우, 커뮤니티 유저 전부 채널 멤버
- 공개 채널일 경우, 관리자만 채널 멤버
> [Server/channel add] 공개채널/비공개채널에 따른 생성 시 채널 유저

- client/src/components/ChannelMetadata/index.tsx
- client/src/components/DMMetadata/index.tsx
- client/src/components/RoomMetadata/index.tsx
> [CLIENT] DM 채팅방 메타데이터 렌더링

- client/src/apis/channel.ts
- client/src/apis/community.ts
- client/src/components/ChannelItem/index.tsx
- client/src/components/Modals/AlertModal/index.tsx
- client/src/hooks/channel.ts
- client/src/hooks/community.ts
- client/src/layouts/CommunityNav/index.tsx
- client/src/layouts/DmNav/index.tsx
- client/src/mocks/data/communities.js
- #165 
커뮤니티 목록에 가져오는 API에 채널 목록이 포함되면서 기존에 있던 get channels API가 삭제되었고, 이를 반영하였습니다.
그 외 SideBar 스타일과 마크업 일부 수정했습니다.
> [CLIENT] 리팩토링

- client/src/mocks/data/communities.js
- client/src/mocks/handlers/Channel.js
- client/src/pages/Channel/index.tsx
- client/src/pages/Community/index.tsx
> [CLIENT] 채팅방 레이아웃

- client/src/apis/chat.ts
- client/src/components/ChatItem/index.tsx
- client/src/hooks/user.ts
- client/src/mocks/data/communities.js
- client/src/mocks/handlers/Channel.js
- client/src/pages/Channel/index.tsx
- client/src/pages/Community/index.tsx
- client/src/pages/Friends/index.tsx
- client/src/utils/date.ts
> [CLIENT] 채팅 메시지 컴포넌트

- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/community/community.service.ts
- server/apps/api/src/community/dto/append-participants-to-community.dto.ts
- server/apps/api/src/community/dto/delete-community.dto.ts
- server/apps/api/src/community/dto/modify-community.dto.ts
- server/apps/api/src/community/helper/makeCommunityObj.ts
- server/apps/api/test/community.service.spec.ts
- server/package.json
- #95 
- #181 
- 사용자 커뮤니티에 추가 시 public 채널에도 자동 추가되도록 로직 변경
- REST API 반영 : _id -> community_id 변경, 특정 커뮤니티 관련은 communities/~~로 변경
- 커뮤니티에 사용자 추가 시 users doc
- channels doc
> [Server/Feature] append user community 기능 추가 구현

- client/src/apis/auth.ts
- client/src/apis/community.ts
- client/src/apis/dm.ts
- client/src/apis/user.ts
- client/src/components/DirectMessageUserItem/index.tsx
- client/src/constants/user.ts
- client/src/hooks/community.ts
- client/src/hooks/useDirectMessagesQuery.ts
- client/src/hooks/useFollowersQuery.ts
- client/src/hooks/useFollowingMutation.ts
- client/src/hooks/useFollowingsQuery.ts
- client/src/hooks/useMyInfoQuery.ts
- client/src/hooks/useUsersQuery.ts
- client/src/layouts/DmNav/index.tsx
- client/src/layouts/Followers/index.tsx
- client/src/layouts/Followings/index.tsx
- client/src/mocks/data/users.js
- client/src/mocks/handlers/DM.js
- client/src/mocks/handlers/Friend.js
- client/src/mocks/handlers/User.js
- #197 
- tokenAxios 적용
- 바뀐 엔드포인트 적용
- 바뀐 API 응답 구조 적용
- dev 버전에서 DM 페이지 사이드바에 동일한 프로필 사진이 뜨는 것은 오류가 아님. mock API에서 사용자 한 명의 정보를 가져오는 API에 대한 응답을 동일한 mock 객체를 넘겼을 뿐임.
> [CLIENT] 배포 버전 프론트 API 점검

- client/src/apis/channel.ts
- client/src/apis/community.ts
- client/src/apis/user.ts
- client/src/constants/endPoint.ts
- client/src/mocks/handlers/Auth.js
- client/src/mocks/handlers/Channel.js
- client/src/mocks/handlers/Community.js
- client/src/mocks/handlers/Friend.js
- client/src/mocks/handlers/User.js
- #200 
end point관련 리팩토링
- 리팩토링 할거 아직 좀 남음
> [CLIENT] endpoint 리팩토링

- server/apps/api/src/auth/auth.controller.ts
- server/apps/api/src/auth/auth.service.ts
- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/channels.controller.ts
- server/apps/api/src/channel/dto/create-channel.dto.ts
- server/apps/api/src/channel/helper/getChannelBasicInfo.ts
- server/apps/api/src/chat-list/chat-list.service.ts
- server/apps/api/src/user/helper/getUserBasicInfo.ts
- server/dao/schemas/channel.schema.ts
- #144
- #186
프론트 측의 요청에 따라 수정하였습니다.
>**채널 정보 전달에 채널 사용자 정보 전달 포함 및 채널 전달 시 chatLists 필드 제거**
>**채널 보낼 때 `channel_id` ->` _id` 로 수정**
- 기존
```
{
"statusCode": 200,
"result": {
"channel_id": "6387339efb6e8c426f157a4e",
"name": "modify311",
"managerId": "637f665d3e13ad0e5b267ed9",
"description": "modify111",
"type": "Channel",
"isPrivate": true,
"users": [ "637f665d3e13ad0e5b267ed9","637f2abb146636e4082885b1"],
"chatLists":[]
}
}
```
- 변경 후
```
{
"statusCode": 200,
"result": {
"_id": "6387339efb6e8c426f157a4e",
"name": "modify311",
"managerId": "637f665d3e13ad0e5b267ed9",
"description": "modify111",
"type": "Channel",
"isPrivate": true,
"users": [
{
"_id": "637f665d3e13ad0e5b267ed9",
"id": "kny@gmail.com",
"nickname": "nayoung",
"status": "ONLINE",
"profileUrl": "url",
"description": …
```
> [Server] 채널 및 유저 API 수정

- .github/workflows/client_dev.yml
> [CLIENT] client-dev workflow 작성

- .github/workflows/server.yml
> secretes fix

- .github/workflows/server.yml
> [DevOps/Fix] docker action

- client/src/apis/auth.ts
- client/src/apis/channel.ts
- client/src/apis/community.ts
- client/src/apis/user.ts
- client/src/constants/endPoint.ts
- client/src/hooks/channel.ts
- client/src/hooks/community.ts
- client/src/hooks/useFollowersQuery.ts
- client/src/hooks/useFollowingMutation.ts
- client/src/hooks/useFollowingsQuery.ts
- client/src/hooks/useReissueTokenMutation.ts
- client/src/hooks/useSignInMutation.ts
- client/src/hooks/useSignUpMutation.ts
- client/src/mocks/handlers/Community.js
- client/src/pages/SignIn/index.tsx
> [CLIENT] 리팩토링 반영

- server/apps/api/src/api.service.ts
> [DevOps]github action pr test

- client/src/apis/chat.ts
- client/src/components/Avatar/index.tsx
- client/src/components/ChatItem/index.tsx
- client/src/components/FollowerUserItem/index.tsx
- client/src/hooks/useUsersQuery.ts
- client/src/layouts/DmNav/index.tsx
- client/src/pages/Channel/index.tsx
- #227 
- 팔로우 기능 추가
- 채팅 메시지 보여줄 때 디테일 수정
- 생성일, 수정일 같으면 수정됨 표시 안함
- 채팅 메시지 받아올 때 채팅 메시지 안 오는 경우 반영
- 삭제일 안 오는 경우 반영
-  url 형식에 안 맞으면 아바타에 mock 이미지 보여줌
- 채널 목록 렌더링하는 동안에도 Direct Message  헤더 보여지도록 수정
> [CLIENT] 배포용 오류 수정 & 팔로우 버튼 추가

- server/apps/api/src/api.service.ts
> PR test for Docker env

- server/apps/api/Dockerfile
> [DevOps] for PR

- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channel.module.ts
- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/helper/getChannelBasicInfo.ts
- server/apps/api/src/chat-list/chat-list.module.ts
- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/helper/getCommunityBasicInfo.ts
- server/apps/api/src/user/helper/getUserBasicInfo.ts
- server/utils/def.ts
- 채널 생성 시 봇 메세지 생성
- 채널 정보 보낼 때 users 정보 제거
- Info를 보낼 때 삭제되었으면 deletedAt 추가
> [Feature/channel] 채널 API 수정

- client/package.json
- client/src/components/ChatForm/index.tsx
- client/src/components/ErrorIcon/index.tsx
- client/src/components/Spinner/index.tsx
- client/src/hooks/useInput.ts
- client/src/index.css
- client/src/layouts/DmNav/index.tsx
- client/src/layouts/Gnb/index.tsx
- client/src/pages/Channel/index.tsx
- yarn.lock
- #226 
채팅 인풋 Form 구현
- 채팅 Form -> textarea기반이고 인풋 영역도 하나이므로 `useForm`대신 `useInput`을 사용하여 간단하게 커스터마이징함.
- 채팅 Form의 최대 높이 지정
- Textarea내용에 따라 높이 자동조절
- 기본 스크롤바 사용함
- Edit Mode를 통해 채팅 수정과 동일한 컴포넌트 사용할 예정, 이를 위해 isDirty가 필요 (바뀌지 않은 값이라면 수정할 수 없도록)
- 레이아웃 버그가 조금 있는데 이건 원인이 뭔지 잘 모르겠어서 일단 놔둘 예정. 혹시 해결법을 아시면 코멘트 부탁드려요. (아래 gif를 보면 채팅 박스 높이가 커짐에 따라 채팅 목록이 자동으로 올라갈 때도 있고, 그렇지 않을 때도 있습니다.)
- 아직 채팅 보내기까지는 구현하지 않았음.
- 미리보기의 `ChatForm`은 `EditMode`로 들어가있음 (실제 코드도 저렇게 되어있긴 한데, 구현하면서 고칠 예정입니다.)
> [CLIENT] 채팅 Form

- server/apps/api/src/auth/auth.controller.ts
- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channels.controller.ts
- server/apps/api/src/chat-list/chat-list.controller.ts
- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/main.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/users.controller.ts
- server/apps/api/src/webhook.interceptor.ts
- server/package.json
- yarn.lock
- #249 
controller layer에서 하던 error logging을 interceptor에서 하도록 일괄 수정
Morgan logging 추가
> [Server/Refactor] error handling interceptor 일괄 처리로 수정

- client/src/pages/NotFound/index.tsx
> [CLIENT] `NotFound` 페이지 작성

- client/config/webpack.common.ts
- client/package.json
- client/src/App.tsx
- client/src/components/ChatForm/index.tsx
- client/src/constants/url.ts
- client/src/hooks/chat.ts
- client/src/hooks/user.ts
- client/src/index.tsx
- client/src/layouts/SocketLayer/index.tsx
- client/src/mocks/data/communities.js
- client/src/mocks/handlers/Channel.js
- client/src/pages/Channel/index.tsx
- client/src/pages/Home/index.tsx
- client/src/queryClient.ts
- client/src/routes/communitiesLoader.ts
- client/src/socketEvents/index.ts
- client/src/stores/socketStore.ts
- client/src/types/apis/process.d.ts
- client/src/types/common/process.d.ts
- client/tsconfig.json
- #248 
채팅 보내기와 소켓 연결을 구현합니다.
- 채팅을 보낼 때 스크롤바를 바닥으로 내려야 함.
- 채팅을 받을 때 스크롤바를 바닥으로 내려야 함.
- 유저가 과거 채팅을 보고 있을 때는 채팅을 받아도 스크롤바를 내리면 안됨
- 채팅을 받을때 스크롤바 위치 조절을 아직 구현하지 않음 -> 채팅 받는 이벤트는 스크롤바를 참조해야 하기 때문에 Channel 페이지에 작성해야함.
- 보낸 채팅을 DB등록에 실패했을 때 수행할 로직을 아직 구현하지 않음
> [CLIENT] 채팅 보내기

- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/community.service.ts
사용자가 아직 커뮤니티에 참가하지 않은 경우, community 정보 전달에 대한 로직 skip
> [Server/fix] 커뮤니티 없을 시 처리 추가

- client/config/webpack.common.ts
- client/package.json
- client/src/apis/chat.ts
- client/src/components/ChatForm/index.tsx
- client/src/components/DirectMessageUserItem/index.tsx
- client/src/constants/endPoint.ts
- client/src/hooks/chat.ts
- client/src/layouts/SocketLayer/index.tsx
- client/src/mocks/handlers/Chat.js
- client/src/pages/Channel/index.tsx
- client/src/pages/SignUp/index.tsx
- client/src/queryClient.ts
- client/src/socketEvents/index.ts
- client/src/stores/chatScrollBarSlice.ts
- client/src/stores/rootStore.ts
- client/src/types/common/index.ts
- client/src/utils/scrollValues.ts
- yarn.lock
- #267 
채팅 받기 기능 추가
- 배포환경에서 테스트해봐야함 (소켓 모킹을 못했습니다)
> [CLIENT] 채팅 받기

- server/apps/api/src/channel/channel.module.ts
- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/helper/addObjectForm.ts
- server/apps/api/src/chat-list/chat-list.controller.ts
- server/apps/api/src/chat-list/chat-list.service.ts
- server/apps/api/src/chat-list/helper/makeChat.ts
- server/utils/def.ts
- 채널 생성 시 botMessage 추가 로직 수정으로 인한 channel 및 chatList 리펙토링
- channelService에서 chatListService에 접근하는 로직을 제거하고 chatListRepository에만 접근하도록 수정
- 봇 메세지 형식 변경
- 채널 생성 시 chat가 추가됨으로 chatList가 비어있을 경우에 대한 예외처리 제거
> [Server/channel, chat] 봇 메세지 추가로 인한 리펙토링

- server/apps/socket/src/axios/request-api-server.ts
- server/apps/socket/src/exceptions/socket-catch-error.ts
- server/apps/socket/src/mock_client/client.js
- server/apps/socket/src/socket.gateway.ts
- server/apps/socket/src/socket.module.ts
- server/apps/socket/src/types.ts
- server/package.json
- shared/socket/NewMessage.ts
- yarn.lock
- #175
- socket 연결 시 access token 유효성 검증하는 middleware 추가
- Socket server로 새로운 메세지 들어왔을 때, API Server로 메세지 저장 요청 로직 추가
- 에러 발생 시 frontend와 협의한 event로 이벤트 전달 `failed-to-send-message`
- access token 만료시 client
- 정상 요청
[ Client ]
[ API server ]
> [Server/Feature] Socket 새 메세지 로직 추가

- .github/workflows/server.yml
- package.json
> [Server/CI,CD] fix: jwt secrete import

- client/src/App.tsx
- client/src/index.tsx
- client/src/layouts/CommunityLayer/index.tsx
- client/src/layouts/SocketLayer/index.tsx
- client/src/pages/Channel/index.tsx
- client/src/socketEvents/index.ts
- #287 
소켓 연결에 Access token 보내기
> [CLIENT] Socket Auth

- .github/workflows/server.yml
- server/apps/socket/Dockerfile
> [Server/Hotfix] socket secrete 반영

- client/src/apis/channel.ts
- client/src/components/ChannelContextMenu/index.tsx
- client/src/components/ChannelInviteBox/index.tsx
- client/src/components/ChannelInviteUserSearchResult/index.tsx
- client/src/components/UserSearchResult/index.tsx
- client/src/constants/endPoint.ts
- client/src/hooks/channel.ts
- client/src/hooks/user.ts
- client/src/mocks/data/users.js
- client/src/mocks/handlers/Channel.js
- client/src/pages/Channel/index.tsx
- client/src/queryKeyCreator.ts
> [CLIENT] 채널 초대하기

- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/channels.controller.ts
- #304 
채널 참가, 초대 시 응답 변경
>**채널 참가**
>**채널 초대**
> [Server/channel] 채널 참가, 초대 API 응답 변경

- .github/workflows/server.yml
- server/apps/api/src/community/communities.controller.ts
- server/apps/api/test/community.e2e-spec.ts
- server/apps/api/test/jest-e2e.json
- server/apps/api/test/user.e2e-spec.ts
- server/custom/pipe/mongodbObjectIdValidation.pipe.ts
- server/package.json
- #no issue
- custom pipe path 변경으로 인한 Test alias path 수정
- jest bug app.getHttpserver 수정
- github action jest 설치시 의존성 문제 해결
> [Server/Hotfix] integration test option 수정

- server/apps/api/src/channel/channel.service.ts
- server/apps/api/src/channel/dto/create-channel.dto.ts
- server/apps/api/src/channel/helper/addObjectForm.ts
- 비공개 채널이 생성되지 않는 이슈 
- 해결 : create-channel.dto 수정
- 커뮤니티에 존재하지 않는 채널에 유저가 초대되고 접속되는 이슈
- 해결 : 초대받고 접속하는 유저가 커뮤니티에 속한 유저인지 확인하는 로직 작성
> [Server/channel] 이슈 해결

- client/src/apis/chat.ts
- client/src/components/ChatItem/ChatActions.tsx
- client/src/components/ChatItem/index.tsx
- client/src/hooks/useHover.ts
> [CLIENT] 채팅 액션 버튼

- client/src/components/ChatItem/index.tsx
- #317 
채팅 복사하기 기능을 구현합니다.
- 복사 로직이 저렇게 되어있는건 `innerText`로 돔 요소 수집시 p태그와 br태그 모두 개행으로 취급되서 불필요한 개행이 과다하게 포함되기 때문입니다.
- 이전 채팅 액션 버튼 커밋이랑 비교해서 실제로는 커밋 1개만 추가되었어요.
> [CLIENT] 채팅 복사

- server/apps/socket/src/axios/request-api-server.ts
- server/apps/socket/src/mock_client/client.js
- server/apps/socket/src/socket.gateway.ts
- shared/socket/NewMessage.ts
- #175 
- 새로운 메세지에 대한 이벤트 일부 수정
- 전송자는 callback 함수 실행하도록 인자 전달
- 채널에 접속한 사용자는 new-message emit
- 에러 발생 시 error throw가 아닌 callback 인자로 전달
> [Server/Feature] socket new message 전달 시 콜백 추가

- .github/workflows/server.yml
- server/apps/api/src/auth/auth.controller.ts
- server/apps/api/src/channel/channel.controller.ts
- server/apps/api/src/channel/channels.controller.ts
- server/apps/api/src/chat-list/chat-list.controller.ts
- server/apps/api/src/community/communities.controller.ts
- server/apps/api/src/community/community.controller.ts
- server/apps/api/src/main.ts
- server/apps/api/src/user/user.controller.ts
- server/apps/api/src/user/users.controller.ts
- server/apps/api/test/community.e2e-spec.ts
- server/apps/api/test/user.e2e-spec.ts
- server/custom/interceptor/api.interceptor.ts
- #249 
- controller response를 전달하는 `responseForm(200, data);` 가 반복되어
- interceptor에서 해당 form으로 만들어 전달하도록 처리
- `responseForm(401, data);` 처럼 statusCode가 다른 경우는 controller에서 기존과 동일하게 보내면, interceptor에서 object에 'statusCode' key가 있는지 확인하여 이중으로 감싸지 않도록 처리
> [Server/Refactor] API Response interceptor

- server/apps/socket/src/axios/request-api-server.ts
- server/apps/socket/src/axios/request-api-urls.ts
- server/apps/socket/src/middleware/authMiddleware.ts
- server/apps/socket/src/mock_client/client.js
- server/apps/socket/src/socket.gateway.ts
- shared/socket/InviteChannel.ts
- shared/socket/index.ts
- #313
- 채널 초대 요청을 socket으로 받도록 처리
- socket에서 api 요청으로 채널 초대
- api 응답을 받아 해당 데이터를 초대받은 사용자들에게 전달
- auth middleware 파일 분리
> [Server/Feature] 실시간 채널 초대를 위한 소켓 이벤트

- client/src/layouts/DmNav/index.tsx
- #309
- DM 기능 넘기기로 했으므로 `GET /api/chanenls/dm` 엔드포인트로 요청하는 부분 삭제
> [CLIENT] `GET /api/chanenls/dm` 엔드포인트로 요청하는 부분 삭제 (#309)

- client/src/components/ChannelLeaveBox/index.tsx
- client/src/components/ChatItem/index.tsx
- client/src/components/ChatList/index.tsx
- client/src/components/ChatRemoveBox/index.tsx
- client/src/hooks/community.ts
- client/src/pages/Channel/index.tsx
- #319 
채팅 삭제하기 모달까지만 구현.
소켓 스펙 명확해질때까지 Submit 로직 구현을 미룰 생각.
> [CLIENT] 채팅 삭제하기 모달

- server/apps/api/src/channel/bot.service.ts
- server/apps/api/src/chat-list/chat-list.controller.ts
- server/apps/api/src/chat-list/chat-list.service.ts
- server/apps/api/src/chat-list/dto/get-message.dto.ts
- server/apps/api/src/chat-list/dto/get-unread-message-point.dto.ts
- server/apps/api/src/chat-list/dto/restore-message.dto.ts
- server/apps/api/src/chat-list/helper/makeChat.ts
- server/custom/pipe/userToSender.pipe.ts
- 채팅 저장 응답 수정
- 채팅 URL 변경
- 채팅 요청 시 Param, Body 이렇게 따로 받아오지 않고 파이프를 활용해 DTO 한번에 받아오도록 수정
>**채팅 저장**
> [Server/Refactor] Chat 리팩토링

- client/public/index.html
- client/src/components/GnbItemContainer/index.tsx
- client/src/index.css
- client/src/layouts/Gnb/index.tsx
- client/tailwind.config.js
> [CLIENT] Tooltip

- server/apps/socket/src/axios/request-api-server.ts
- server/apps/socket/src/axios/request-api-urls.ts
- server/apps/socket/src/axios/request-api.method.ts
- server/apps/socket/src/axios/requet-api-body.ts
- server/apps/socket/src/mock_client/client.js
- server/apps/socket/src/socket.gateway.ts
- shared/socket/DeleteMessage.ts
- shared/socket/ModifyMessage.ts
- shared/socket/NewMessage.ts
- shared/socket/index.ts
- #175 
- #312
- #314  
- socket new-message event 명세 변경
client > socket
```tsx
helloSocket.emit(
'chat',
{
chatType: 'new'
channelId: string,
content: string,
} as data,
callback,
);
```
socket > client
```tsx
전송자: { written: true; chatInfo : apiResult } | { written: false }
그 외 다른 채팅방 사용자 : helloSocket.on('new-chat', apiResult );
```
- socket modify-message event 작성
client > socket
```tsx
helloSocket.emit(
'chat',
{
chatType: 'modify'
channelId: string,
chatId: string,
content: string,
} as data,
callback,
);
```
socket > client
```tsx
전송자: { written: true; chatInfo : apiResult } | { written: false }
그 외 다른 채팅방 사용자 : helloSocket.on('modify-chat', apiResult );
```
- socket delete-message event 작성 ( socket > api 미검증)
client > socket
```tsx
helloSocket.emit(
'chat',
{
chatType: 'delete' …
```
> [Server/Feature] 소켓 채팅 생성 data type 변경, 채팅 수정 로직

- client/src/components/ChatItem/index.tsx
- client/src/components/ChatRemoveBox/index.tsx
- client/src/components/UserActionBox/index.tsx
- client/src/errors/defaultSocketErrorHandler.ts
- client/src/hooks/chat.ts
- client/src/layouts/SocketLayer/index.tsx
- client/src/pages/Channel/index.tsx
- client/src/sockets/ClientIO.ts
- client/src/sockets/ClientIOTypes.ts
- client/src/stores/socketStore.ts
> [CLIENT] 채팅 삭제

- client/src/constants/endPoint.ts
- client/src/constants/regex.ts
- client/src/hooks/channel.ts
- client/src/layouts/SocketLayer/index.tsx
- client/src/mocks/handlers/Friend.js
- client/src/pages/Channel/index.tsx
- client/src/sockets/ClientIOTypes.ts
> [CLIENT] 엔드포인트 변경, 기타 리팩토링

- client/public/index.html
- client/src/components/ChatItem/index.tsx
- client/src/components/ChatRemoveBox/index.tsx
- client/src/components/CommunityLeaveBox/index.tsx
- client/src/components/GnbItemContainer/index.tsx
- client/src/hooks/chat.ts
- client/src/pages/Channel/index.tsx
- #353 
툴팁 DOM 참조오류, 커뮤니티 퇴장 소켓 disconnect, 채팅 탐색 개선, 소켓 연결 조건문 오타 수정
> [CLIENT] 툴팁 DOM 참조오류, 커뮤니티 퇴장 소켓 disconnect, 채팅 탐색 개선, 소켓 연결 조건문 오타 수정

- client/src/components/ChatItem/index.tsx
- #360 
`chat.type` === `SYSTEM`이면 시스템 봇으로 나타냄
> [CLIENT] 시스템 봇

- server/apps/socket/src/axios/request-api-server.ts
- server/apps/socket/src/mock_client/client.js
- docker 내부 localhost 오류 해결: 주소 대신 타겟 컨테이너 이름 작성
> [Server/Hotfix] docker 내부 localhost 오류 해결: 주소 대신 타겟 컨테이너 이름 작성

- client/src/components/ChatItem/index.tsx
- client/src/sockets/ClientIO.ts
> [CLIENT] 재전송 버튼

- server/apps/api/src/auth/helper/signToken.ts
- server/apps/api/src/chat-list/chat-list.module.ts
- server/apps/api/src/chat-list/chat-list.service.ts
- server/dao/repository/chat-list.respository.ts
- accessToken 만료시간 업데이트 (15m -> 1hr)
- 코드리뷰에 따른 수정
- 채팅 수정, 삭제 시 DB에 저장된 값을 가져와서 응답하도록 수정
- #358 
- 커뮤니티 관리자, 채널 관리자 채팅 삭제 권한 부여
> [Server/chat] accessToken 만료시간 업데이트 및 채팅 리팩토링

- server/apps/api/src/channel/bot.service.ts
- server/apps/api/src/channel/helper/getKoreanTime.ts
- server/apps/api/src/channel/helper/index.ts
> [Server/chat] 봇 메세지 한국 시간으로 수정

- client/src/components/Avatar/index.tsx
- client/src/components/ChatItem/index.tsx
- client/src/constants/user.ts
- client/src/hooks/chat.ts
- client/src/layouts/CommunityNav/index.tsx
> [CLIENT] 채팅 재전송

- client/src/layouts/DmNav/index.tsx
DM 페이지 타이틀을 Direct Message에서 Asnity로 변경
> [CLIENT] DM 페이지 타이틀을 Asnity로 변경

- client/src/components/ChannelLeaveBox/index.tsx
- client/src/components/CommunityLeaveBox/index.tsx
- client/src/components/Modals/ContextMenuModal/index.tsx
- client/src/components/UserActionBox/index.tsx
- client/src/components/UserProfile/index.tsx
- client/src/constants/user.ts
- client/src/hooks/auth.ts
- client/src/hooks/community.ts
- client/src/layouts/ChannelInfoLayer/index.tsx
- client/src/layouts/CommunityNav/index.tsx
- client/src/layouts/Gnb/index.tsx
- client/src/layouts/SocketLayer/index.tsx
- client/src/pages/Channel/index.tsx
- client/src/sockets/ClientIO.ts
- client/src/stores/socketStore.ts
> [CLIENT] 여러 버그 수정

- client/src/layouts/DmNav/index.tsx
- client/src/layouts/Gnb/index.tsx
> [CLIENT] Direct Message 툴팁과 아바타를 Asnity로 변경

- client/src/components/FollowerUserSearchResult/index.tsx
- client/src/components/FollowingUserSearchResult/index.tsx
- client/src/components/UserActionBox/index.tsx
- client/src/components/UserSearchResult/index.tsx
> [CLIENT] 팔로워, 팔로잉, 유저검색 UI 버그 수정

- client/src/hooks/combine.ts
- client/src/hooks/useInterval.ts
- client/src/pages/Home/index.tsx
> [CLIENT] Communities interval 리팩토링

- README.md
> docs: README 발표 영상 및 발표 PPT 수정

- server/.gitattributes
> [Hotfix] Repository language 분포 제한 설정

- .github/workflows/server.yml
- server/apps/api/Dockerfile
> [Server/Fix] main merge 시 deploy되도록 변경

- client/src/components/Form/SignInForm.tsx
- client/src/components/__tests__/SignInForm.spec.tsx
- client/src/components/__tests__/SignUpForm.spec.tsx
- client/src/pages/SignIn/index.tsx
- #412 
`SignInForm` Test
- 테스트 코드 작성을 위해 SignInForm을 SignIn 페이지에서 분리하였습니다.
- SignIn 페이지가 아니라 SignInForm 컴포넌트를 테스트했습니다.
- `SignUpForm.spec.tsx`에서 `renderSignUpPage`를 `renderSignUpForm`으로 변경하였습니다.
> [CLIENT] SignInForm 컴포넌트 테스트

- client/src/hooks/auth.ts
- client/src/layouts/Gnb/index.tsx
- client/src/pages/AuthorizedLayer/index.tsx
- client/src/pages/Error/index.tsx
- client/src/pages/Root/index.tsx
- client/src/pages/SignIn/index.tsx
- client/src/pages/UnAuthorizedLayer/index.tsx
> [CLIENT] Auth 관련 리팩토링
