client/package.json, server/package.json, yarn.lock
- common 워크스페이스 이름을 shared로 수정 
- 기존의 common이 남아있으면 실제 존재하는 common 라이브러리로 인식하기 때문에 문제 발생할 수 있어서 급하게 수정합니다.
- 백엔드 브랜치 머지할 때 충돌 날 것임.
=> [Client] Workspace common의 이름을 shared로 변경

server/apps/api/src/main.ts, server/apps/api/src/user/dto/user-basic-info.dto.ts, server/apps/api/src/user/user.controller.ts, server/apps/api/src/user/user.service.ts, server/custom_pipe/mongodbObjectIdValidation.pipe.ts, server/dao/repository/user.repository.ts, server/package.json, server/tsconfig.json
- #22 
- 특정 사용자 정보 요청시 data 전달
- 정상
- 없는 사용자
- object id 형식이 아닐 때
=> [Server] Feature/find user

client/src/common/components/Avatar/index.tsx, client/src/common/components/CommunityAvatar/index.tsx, client/src/common/components/UserAvatar/index.tsx
- #41 
Closes #41
- 공통 컴포넌트인 아바타, 커뮤니티 아바타, 유저 아바타를 작성하였음.
=> [CLIENT] 공통 컴포넌트 - 아바타, 커뮤니티 아바타, 유저 아바타 작성

server/apps/api/src/auth/auth.controller.ts, server/apps/api/src/auth/auth.module.ts, server/apps/api/src/auth/guard/auth.guard.ts, server/apps/api/src/auth/guard/index.ts, server/apps/api/src/auth/strategy/auth.strategy.ts, server/apps/api/src/auth/strategy/index.ts
- #11 
AccessToken이 유효한지 검증하는 strategy, guard 생성
**자기 자신에 대한 정보를 가져오는 API 실행시**
- 유효한 accessToken
- 유효하지 않은 accessToken
- accessToken은 유효하지만 user정보가 DB에 없음
=> [Server/auth] accessToken 유효한지 검증 로직 작성

server/apps/api/src/auth/auth.controller.ts, server/apps/api/src/auth/auth.module.ts, server/apps/api/src/auth/auth.service.ts, server/apps/api/src/auth/guard/index.ts, server/apps/api/src/auth/guard/jwt-access.guard.ts, server/apps/api/src/auth/guard/jwt-refresh.guard.ts, server/apps/api/src/auth/helper/signToken.ts, server/apps/api/src/auth/strategy/index.ts, server/apps/api/src/auth/strategy/jwt-access.strategy.ts, server/apps/api/src/auth/strategy/jwt-refresh.strategy.ts, server/apps/api/src/main.ts, server/package.json
- #11 
- #17 
refreshToken을 통해 accessToken을 재발행 하는 로직 구현
로그아웃시, user DB에서 refreshToken 제거
- cookie에 저장된 refreshToken을 사용하기 위한 cookieParser 미들웨어 적용
- refreshToken검증을 위한 Guard, Strategy 생성
- DB에 저장된 refreshToken과 쿠키에 있는 refreshToken이 일치하는지 확인
- 일치하면 accessToken 재발행
- 유효한 refreshToken
- 유효한 refreshToken 하지만 DB에 저장된 refreshToken과 일치하지 않음
- 유효한 refreshToken 하지만 user정보가 DB에 없음
- 유효하지 않은 refreshToken
refreshToken 만료시간이 기존에 1시간 이었는데, 너무 작아서 100시간으로 수정했습니다!
=> [Server/auth] accessToken 재발행 로직 구현, 로그아웃 로직 구현

client/src/apis/auth.ts, client/src/constants/regex.ts, client/src/errors/defaultErrorHandler.ts, client/src/hooks/useSignUpMutation.ts, client/src/pages/SignUp/index.tsx, client/src/queryKeyCreator.ts, client/src/types/apis/response.ts, client/tsconfig.json
=> [CLIENT] 회원가입 페이지 리팩토링

server/apps/api/src/auth/strategy/jwt-access.strategy.ts, server/apps/api/src/community/community.controller.ts, server/apps/api/src/community/community.service.ts, server/apps/api/src/community/dto/delete-community.dto.ts, server/apps/api/src/community/dto/index.ts, server/apps/api/src/user/dto/index.ts, server/apps/api/src/user/user.controller.ts, server/apps/api/src/user/user.service.ts, server/dao/repository/community.repository.ts, server/dao/repository/user.repository.ts, server/dao/schemas/channel.schema.ts, server/dao/schemas/user.schema.ts
- #115 
- 사용자 스키마 내부의 커뮤니티 스키마 변경
```
communities : {
_id : {
_id : _id, (community _id)
channels : {
_id : {  _id (channel _id), lastRead: Date }
}
}
}
```
- throw error 일원화
=> [Server/Feature] get communities 중간 merge

server/apps/api/src/channel/channel.module.ts, server/apps/api/src/channel/dto/channel-basic-info.dto.ts, server/apps/api/src/community/community.module.ts, server/apps/api/src/community/community.service.ts, server/apps/api/src/community/dto/community-basic-info.dto.ts, server/dao/repository/channel.repository.ts
- #115 
현재 사용자가 속한 커뮤니티 및 채널들의 기본 Data form 완성하였으며,
[이전 PR](https://github.com/boostcampwm-2022/web24-Asnity/pull/129) 과 이어집니다.
커뮤니티 기본 정보 form
```
return {
_id: community._id,
name: community.name,
managerId: community.managerId,
profileUrl: community.profileUrl,
description: community.description,
channels,
};
```
커뮤니티 내 채널 기본 정보 from
```
return {
_id: channel._id,
name: channel.name,
managerId: channel.managerId,
type: channel.type,
isPrivate: channel.isPrivate,
profileUrl: channel.profileUrl,
description: channel.description,
lastRead: boolean
};
```
- 정상 동작
-  사용자 doc 내부 communit _id 이상
- 사용자 doc 내부 적힌 채널 _id 이상
- 사용자 doc 내부 적힌 채널 _id가 실제 커뮤니티 doc에 없을 때
=> [Server/Feature] 현재 사용자가 속한 커뮤니티 및 채널들의 기본 정보 전달

client/src/apis/channel.ts, client/src/components/ChannelItem/index.tsx, client/src/hooks/channel.ts, client/src/layouts/CommunityNav/index.tsx, client/src/mocks/data/channels.js, client/src/mocks/handlers/Channel.js, client/src/mocks/handlers/index.js, client/src/mocks/utils/rand.js, client/src/queryKeyCreator.ts
- #151 
커뮤니티 페이지에 들어가면 채널 목록을 사이드바에 렌더링한다.
=> [CLIENT] `CommunityNav` 채널 목록 보여주기

server/apps/api/src/auth/strategy/jwt-access.strategy.ts, server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/dto/exit-channel.dto.ts, server/apps/api/src/channel/helper/addObjectForm.ts, server/dao/repository/channel.repository.ts
- #143
- #11 
- 채널 퇴장 로직 작성
- channel 도큐먼트의 users 필드에서 사용자 제거
- user 도큐먼트의 communities:channels 필드에서 사용자 제거
- Access Token을 검증할 때 DB에서 user가 존재하는 지 확인하는 로직 제거
- DB에 접근하게 되면 JWT의 장점(토큰을 복호화하면 정보를 알 수 있어서 서버 부담 줄이는)을 없앤다고 생각함
- "확인하는 로직이 없으면 사용자가 악용하면 어떻게 하지?" 라는 의문이 생김
- JWT안에 유저 정보가 암호화 되어있음, 서버의 secret key가 없으면 해독 불가능 -> JwtAccessGuard가 잘못된 accessToken이면 unauthorization 에러를 내보내서 그럴 일은 거의 없을 것
채널 퇴장 성공 시
관리자가 채널 삭제 시 로직은 내일 회의 때 클라이언트에서 처리할 지 서버에서 처리할 지 얘기 나눠보고 구현할께요!
- 채널에 혼자 존재 : 삭제 가능
- 채널에 다른 유저 존재 : 관리자 변경 필요
- 클라이언트에서 해준다면, 관리자 변경을 클라이언트에서 요청을 보내고 성공하면 삭제요청을 보냄
- 서버에서 해준다면, 관리자가 삭제를 요청한다고 에러처리 필요
=> [Server/channel exit] 채널 퇴장 로직 구현 및 accessToken 검증 로직 수정

server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/dto/delete-channel.dto.ts, server/apps/api/src/channel/dto/exit-channel.dto.ts, server/apps/api/src/channel/dto/index.ts, server/dao/repository/channel.repository.ts
- #144 
- #145 
- 채널 정보 전달하는 로직 구현 (`GET api/channel/:id`)
- 채널 삭제하는 로직 구현 (`DELETE api/channel/:channel_id`)
>**채널 정보 전달** 
- #144 
- `Get api/channel/:id`
- getChannelInfo
- getChannelInfo
- ~~ChannelBasicInfo로 감싸기~~
- findOne
- ~~채널 id가 존재하지 않으면 에러~~
>**채널 삭제**
```tsx
channel_id: String, NotEmpty
user_id: String, NotEmpty
```
- `Delete /api/channel/:channel_id`
- `UseGuard(JwtAccessGuard)`
- deleteChannel
- channel에 속한 user들에 대하여
- user 도큐먼트에 community 필드에 channelId 제거
- channel도큐먼트 softDelete
- userId가 채널의 managerId와 일치하지 않으면 에러
>**채널 정보**
- 성공
>**채널 삭제**
- 성공
- 실패 (채널 관리자가 아닐 경우)
=> [Feature/channel] 채널 정보 API, 채널 삭제 API 구현

client/src/apis/channel.ts, client/src/apis/community.ts, client/src/apis/user.ts, client/src/components/ChannelItem/index.tsx, client/src/components/ChannelMetadata/index.tsx, client/src/hooks/channel.ts, client/src/hooks/community.ts, client/src/hooks/user.ts, client/src/layouts/CommunityNav/index.tsx, client/src/mocks/handlers/Channel.js, client/src/mocks/handlers/Community.js, client/src/mocks/handlers/User.js, client/src/pages/Channel/index.tsx, client/src/queryKeyCreator.ts, client/src/utils/date.ts
- #156 
- 채널방 시작에서 채널 생성일, 채널 생성한 사람, 채널 이름 등을 표시한다.
- 단수/복수
- `id`/`_id`
등등 일관적이지 않은 부분이 있어 현재 postman과 다른 명세 사용하는 API 있음
~~postman에 현재 없는 API도 있음(`/api/communities/:communityId`)~~
`/api/user/communities`에서 가져오기로 수정
나중에 리팩토링할 때 querykey도 일관적이게 바꿔야함
특히 cursor를 넘기거나 filter를 넘기는 경우 일관적인 기준이 필요함
=> [CLIENT] Channel metadata 렌더링

client/src/apis/community.ts, client/src/components/AlertBox/index.tsx, client/src/components/CommunityContextMenu/index.tsx, client/src/components/Modals/AlertModal/index.tsx, client/src/components/Modals/ContextMenuModal/index.tsx, client/src/hooks/community.ts, client/src/layouts/Gnb/index.tsx, client/src/mocks/handlers/Community.js, client/src/mocks/utils/logging.js, client/src/pages/Home/index.tsx, client/src/queryKeyCreator.ts, client/src/stores/alertModalSlice.ts, client/src/stores/contextMenuModalSlice.ts, client/src/stores/rootStore.ts
- #157 
- #162 
커뮤니티 모달과 커뮤니티 퇴장 기능까지 구현하였습니다. 원래는 이 둘을 나눠서 PR 올리려고 했는데, 퇴장 기능 구현하면서 모달에 전달하는 상태 타입들이 바뀌어서 한번에 올립니다.
커뮤니티 퇴장을 삭제랑 헷갈려서 커뮤니티 삭제 `api`까지 넣었습니다. (기능은 구현 X)
참고로, Mock API로 테스트할 때는 커뮤니티 퇴장 후, 모킹 데이터인 `communities`배열을 업데이트하지 않아서 `refetch`되면 원 상태로 돌아오긴 합니다. 
선언을 `let`으로 바꾸고 `filter`메서드로 제거하려고 했었는데, 런타임에 자꾸 오류가 뜨더라구요.
=> [CLIENT] 컨텍스트 메뉴 모달, 커뮤니티 퇴장하기

server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/dto/index.ts, server/apps/api/src/channel/dto/invite-channel.dto.ts
- #112 
비공개 채널에 사용자를 추가하기 위한 API
```
communityId: String, NotEmpty
channelId: String, NotEmpty
userId: String, NotEmpty
```
- `POST /api/channel/invite`
- `UseGuards(JwtAccessGuard)`
- inviteChannel
- user 도큐먼트에 community 필드에 channelId 삽입
- channel에 user 삽입
- 채널 초대 성공
=> [Server/channel invite] 채널 초대 API

server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/dto/index.ts, server/apps/api/src/channel/dto/update-last-read.dto.ts
- #177 
안읽은 메세지 구현을 위한 API
다른 채널로 이동 시, 이전 채널의 마지막 접속시간 업데이트
```tsx
community_id: NotEmpty, String
channel_id: NotEmpty, String
```
- api/channel/update/lastRead
- user 도큐먼트의 community:channel 필드 현재시간으로 업데이트
- 업데이트 성공시
=> [Server/channel update last read] 마지막 채널 접속시간 업데이트 API

server/apps/api/src/auth/auth.controller.ts, server/apps/api/src/auth/auth.service.ts, server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.module.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/channels.controller.ts, server/apps/api/src/channel/dto/delete-channel.dto.ts, server/apps/api/src/channel/dto/exit-channel.dto.ts, server/apps/api/src/channel/dto/invite-channel.dto.ts, server/apps/api/src/channel/dto/modify-channel.dto.ts, server/apps/api/src/channel/dto/update-last-read.dto.ts, server/apps/api/src/channel/helper/addObjectForm.ts, server/dao/schemas/user.schema.ts
- #124 
- #181 
- #187 
- auth: 버그 수정 및 에러 발생 시 로그로 출력되게 수정
- channel: 대규모 리펙토링 (내용은 아래와 같음)
>**버그 수정**
- 사용자 회원가입 시 STATUS가 `OFFLINE` 으로 설정
- 사용자 로그인 시 STATUS가 `ONLINE` 으로 변환
- 사용자 로그아웃 시 STATUS가 `OFFLINE` 으로 변환
- 관리자가 채널 탈퇴 시
- 채널 user가 2명 이상 -> error 처리
- 채널 user가 1명 -> 채널 삭제
- 채널 삭제 시 community에서 채널 삭제 로직 누락된거 수정
>**리펙토링**
- REST API 네이밍 규칙에 따라 API URL 수정
- 일관성을 위한 변수명 수정
- API URL 수정에 따라 `channel.controller` -> `channel.controller`, `channels.controller` 로 분리
- service에서 코드 간결화를 위해 dto로 받은 거 변수로 저장해서 사용
제가 API URL을 잘 못 짰다는 것을 어제 공부해서 알게되었습니다 ㅠㅠ (지적해주셔서 감사합니다!)
API URL 변경에 따른 혼란을 줘서 죄송합니다 🙇‍♂️🙇‍♂️
=> [Server] 유저 버그 수정 및 채널 리펙토링

server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/channels.controller.ts, server/apps/api/src/channel/dto/index.ts, server/apps/api/src/channel/dto/join-channel.dto.ts, server/apps/api/src/channel/dto/modify-channel.dto.ts
- #195 
커뮤니티 사용자는 공개 채널에 참여할 수 있다.
채널 정보 수정 시, 매니저 ID 수정이 누락 된 버그 수정
- `POST api/channels/:channel_id`
- `UseGuards(JwtAccessGuard)`
- joinChannel
- channel 도큐먼트의 users 필드 업데이트
- user 도큐먼트의 community:channel 필드 업데이트
=> [Server/channel join] 채널 접속 API

client/src/apis/chat.ts, client/src/components/ChannelMetadata/index.tsx, client/src/components/ChatItem/index.tsx, client/src/components/DMMetadata/index.tsx, client/src/hooks/chat.ts, client/src/hooks/useIsIntersecting.ts, client/src/mocks/data/chats.js, client/src/mocks/handlers/Chat.js, client/src/mocks/handlers/index.js, client/src/pages/Channel/index.tsx, client/src/queryKeyCreator.ts, client/src/utils/date.ts
- #183 
- 사용자가 스크롤을 위로 올리면 이전 메시지를 받아오는 무한 스크롤을 적용하였음.
- 채팅 메시지 항목들 가장 위에 Intersection Observer에 의해 관찰되는 `<div />` 요소를 끼워놓고, 해당 요소가 view port에 노출되면 이전 페이지들을 fetch해오는 방식임.
- 채팅방 들어가자마자 요소가 노출되어 fetch해옴 =>**첫번째 페이지 렌더링 후 스크롤을 아래로 내려 요소가 노출되지 않도록 해야함**
=> [CLIENT] 채팅방 무한 스크롤 적용

client/src/apis/channel.ts, client/src/apis/chat.ts, client/src/apis/user.ts, client/src/components/ChannelMetadata/index.tsx, client/src/components/ChatItem/index.tsx, client/src/constants/endPoint.ts, client/src/hooks/user.ts, client/src/layouts/DmNav/index.tsx, client/src/mocks/data/chats.js, client/src/mocks/data/communities.js, client/src/mocks/data/users.js, client/src/mocks/handlers/Channel.js, client/src/mocks/handlers/Chat.js, client/src/mocks/handlers/Friend.js, client/src/mocks/handlers/User.js, client/src/pages/Channel/index.tsx, client/src/queryKeyCreator.ts
- #213
- GET `/api/users/:userId` API는 제공되지 않으므로 GET `/api/channels/:channelId/usrs` API를 사용하도록 변경
=> [CLIENT] GET `/api/users/:userId` API 사용하던 부분 GET `/api/channels/:channelId/usrs` API 사용하도록 변경

client/src/apis/channel.ts, client/src/components/ChannelContextMenu/index.tsx, client/src/components/ChannelLeaveBox/index.tsx, client/src/constants/endPoint.ts, client/src/hooks/channel.ts, client/src/mocks/handlers/Channel.js, client/src/queryKeyCreator.ts
- #254 
- 채널 컨텍스트 메뉴에서 채널 나가기 버튼 클릭 시 채널 나가기 모달 활성화
- 채널 나가기 모달에서 확인 버튼을 눌러 채널 나가기
- 취소 버튼을 누르며 모달 닫기
optimistic update해주는 거랑 그러지 않는 경우 구분하면 좋을듯
=> [CLIENT] 채널 나가기

client/src/App.tsx, client/src/hooks/community.ts, client/src/layouts/ChannelLayer/index.tsx, client/src/layouts/CommunityLayer/index.tsx
- #257 
path param의 커뮤니티 아이디와 채널 아이디가 올바르지 않으면 `/dms`로 리다이렉트한다.
캐싱을 고려하여 getQueryData로 가져올건지 useQuery로 가져올 건지 Map으로 가져올 건지 배열로 가져올 건지 일관된 리팩토링 필요함
=> [CLIENT] 커뮤니티 아이디, 채널 아이디 path params 검증

server/apps/api/src/chat-list/chat-list.controller.ts, server/apps/api/src/chat-list/dto/restore-message.dto.ts
- 채팅에 관련한 API url 변경
- 채팅 저장 : `POST /api/chat/:channel_id` -> `POST /api/channels/:channel_id/message`
- 채팅 받아오기 : `GET /api/chat/:channel_id` -> `GET /api/channels/:channel_id/message`
- 안 읽은 채팅 위치 : `GET /api/chat/:channel_id/unread-message` -> `GET /api/channels/:channel_id/unread-message`
- 채팅 저장 dto 변경 (senderId를 accessToken을 확인해서 받아옴)
- 수정 전 : type, content, senderId
- 수정 후 : type, content
=> [Server/chat] api url 및 채팅 저장 dto 변경

server/apps/api/src/chat-list/chat-list.controller.ts
오타로 인한 오류였습니다..😓
`req.user_id` -> `req.user._id`
=> [Server/chat] 채팅 저장 시 accessToken에서 유저 정보 받아오지 않는 오류 해결

server/apps/api/src/channel/channel.service.ts
객체 내부에는 변할 수 있는 값이어서 타입을 명확히 추론하지 않고 포괄적으로 추론을 하여 발생한 이유였습니다.
`{} as const` 를 활용하여 타입을 명확히 했습니다.
=> [Server/channel] 타입 에러 해결

client/src/components/ChatList/index.tsx, client/src/components/CommunityInviteUserSearchResult/index.tsx, client/src/components/FollowerUserSearchResult/index.tsx, client/src/components/FollowingUserSearchResult/index.tsx, client/src/components/UserSearchResult/index.tsx, client/src/hooks/channel.ts, client/src/hooks/community.ts, client/src/hooks/useFollowersQuery.ts, client/src/hooks/useFollowingsQuery.ts, client/src/hooks/user.ts, client/src/layouts/CommunityNav/index.tsx, client/src/pages/Channel/index.tsx
=> [CLIENT] `select` 옵션에서 `Record<id, 데이터>` 형태로 내보내어 탐색 개선

client/src/apis/chat.ts, client/src/components/Avatar/index.tsx, client/src/components/ChatContent/index.tsx, client/src/components/ChatItem/index.tsx, client/src/hooks/chat.ts, client/src/layouts/SocketLayer/index.tsx, client/src/mocks/data/users.js, client/src/pages/Channel/index.tsx, client/src/pages/Friends/index.tsx
- #281 
채팅 전송 실패시 에러 핸들링
- 개행
- 보내는중
- 전송 실패 및 삭제
- 채널 이동시 채팅 데이터가 언마운트되는데, 이 때 소켓 Emit Callback이 유지되는지는 의문입니다. 테스트해볼 필요 있어요.
=> [CLIENT] 채팅 전송 에러 핸들링

server/apps/api/src/community/communities.controller.ts, server/apps/api/src/community/community.controller.ts, server/apps/api/src/community/community.service.ts, server/apps/api/src/community/dto/append-participants-to-community.dto.ts, server/apps/api/src/community/dto/create-community.dto.ts, server/apps/api/src/community/dto/delete-community.dto.ts, server/apps/api/src/community/dto/modify-community.dto.ts, server/apps/api/src/community/dto/request-user-about-community.dto.ts
- #291 
- 커뮤니티에서 클라이언트로부터 오는 데이터(Param, Body, Req)를 커스텀 데코레이터를 사용하여 DTO를 한번에 받도록 리팩토링
- DTO 수정
- mongoId를 받아오는 값들 `@IsString` -> `@IsMongoId`로 수정
- @ReceivedData()로 한번에 데이터를 받아와서 필수 값들 `@IsOptional` -> `@IsNotEmpty`로 수정
=> [Server/community] DTO를 한번에 받도록 리팩토링

client/src/components/ChannelInviteUserSearchResult/index.tsx, client/src/components/ChatItem/index.tsx, client/src/layouts/SocketLayer/index.tsx, client/src/pages/Friends/index.tsx, client/src/socketEvents/index.ts
- #295 
- 채널 초대 시 API 요청하지 않고 소켓 이벤트 발생시키는 것으로 변경
- 채널 초대 받으면 queryClient에 반영하도록 함
~~채널 초대 받은 클라이언트에서 queryClient에 반영하는 방법~~
- ~~현재는 커뮤니티 아이디를 받아오지 않으므로 `invalidateQueries`로 반영함~~
- ~~커뮤니티 아이디 받으면 `setQueryData`로 반영하도록 바꿔야함~~
=> 커뮤니티 아이디 받으므로 `setQueryData`로 `queryClient`에 반영
=> [CLIENT] 채널 초대 소켓 이벤트

server/apps/api/src/channel/bot.service.ts, server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.module.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/channel/dto/create-channel.dto.ts, server/apps/api/src/channel/helper/getChannelBasicInfo.ts, server/apps/api/src/chat-list/dto/restore-message.dto.ts, server/apps/api/src/main.ts, server/custom/decorator/ReceivedData.decorator.ts, server/utils/def.ts
- #279 
봇 메세지 처리 로직을 channel 서비스에서 다른 서비스로 분리
아까 나누고 싶다던 의견입니다.
봇을 원래 helper에 넣으려고 했는데, repository에 접근을 해서 로직을 수행하기 때문에 service로 만들었습니다. 
service에서 service를 불러오는 것 같아 좋은 코드라 생각이 들지는 않는데 어떻게 생각하시나요??
아니면 controller에서 두개의 service로 불러오는 방식도 괜찮을꺼 같아요.
=> [Server/channel] Bot을 channel 서비스에서 다른 서비스로 분리

server/apps/api/src/channel/helper/addObjectForm.ts
- 채널 이탈 시 communities:_id가 사라지는 이슈 해결
- 이슈 원인 : delete할 때 addObjectForm.ts를 사용하여 _id도 지워졌습니다.
- 해결 : 방금 이슈의 해결책으로 착각하여 생성한 addObjectForm.ts의 _id를 넣어주는 부분을 제거했습니다.
- 제거해도 괜찮은 이유 : 방금 이슈는 community에 사용자가 존재하지 않아서 발생한건데 community에 존재하지 않으면 에러를 발생하게 해서 해결했습니다.
=> [Server/channel] 채널 이탈 시 버그 해결

client/src/apis/channel.ts, client/src/components/Avatar/index.tsx, client/src/components/ChannelItem/index.tsx, client/src/constants/endPoint.ts, client/src/hooks/channel.ts, client/src/hooks/chat.ts, client/src/layouts/CommunityNav/index.tsx, client/src/layouts/Gnb/index.tsx, client/src/layouts/SocketLayer/index.tsx, client/src/mocks/handlers/Channel.js, client/src/pages/Channel/index.tsx, client/src/queryKeyCreator.ts
- #315 
- 채널 입장, 퇴장시 방문 시각을 업데이트하는 API 요청을 보낸다.
- 안 읽은 메시지가 있으면 Gnb와 사이드바에 표시한다.
- 새로 들어오는 메시지가 있을 때 현재 보고 있는 채널이 아니면 안 읽은 메시지가 있다고 Gnb와 사이드바에 표시한다.
- 현재 방문 시각 업데이트하는 API가 엔드포인트만 뚫려있고 로직은 구현이 안되어있음 그래서 읽어도 refetch해오면 다시 플래그가 띄워짐
- `lastRead` 프로퍼티를 `existUnreadChat`으로 바꾼다고 함 근데 API에 반영이 안되어있음 반영 후에 바꿔줘야함
- **채널 페이지 입장시 안 읽은 메시지의 첫번째 인덱스를 받아오는 API 호출해서 채널 아이템에 표시해주는 건 구현 안했음**
=> [CLIENT] 안 읽은 메시지 Gnb와 사이드바에 표시

client/src/App.tsx, client/src/apis/chat.ts, client/src/components/ChatForm/index.tsx, client/src/components/ChatItem/index.tsx, client/src/components/GnbItemContainer/index.tsx, client/src/components/UserActionBox/index.tsx, client/src/hooks/chat.ts, client/src/layouts/SocketLayer/index.tsx, client/src/mocks/data/chats.js, client/src/mocks/handlers/Chat.js, client/src/pages/Channel/index.tsx, client/src/routes/HomeErrorElement.tsx, client/src/socketEvents/clientIO.ts, client/src/socketEvents/index.ts, client/src/utils/dom.ts
- #318
채팅 수정만 하려고 했는데, 도중에 슬랙으로 버그 제보(/dms -> /무한루프)가 와서 그것까지 마저 수정하였습니다.
- 초기에는 `fakeChatId`로 렌더링해주는데, 이후에 수정 및 삭제에서 채팅 아이디를 전달하기 위해서는 `realChatId`가 필요함.
- 채팅 수정 성공
- 채팅 수정 실패
- 다른 사람의 채팅 수정 반영
- new Chat은 기본적으로 마지막 페이지에 추가됩니다. 그래서 페이지 탐색이 필요 없습니다.
- edit Chat은 어떤 채팅이 수정될 지 모르기 때문에, 수정된 채팅이 어떤 페이지에 존재하는지 탐색이 필요합니다. 
- 채팅이 인덱스번호를 아이디로 가져서 효율적인 탐색 가능
- 이 탐색 로직을 공통 함수로 분리
- 채팅 수정 취소는 취소버튼 누르거나 ESC 누르면 취소됩니다.
=> [CLIENT] 채팅 수정

client/src/App.tsx, client/src/pages/AuthorizedLayer/index.tsx, client/src/pages/Error/index.tsx, client/src/pages/NotFound/index.tsx, client/src/pages/UnknownError/index.tsx, client/src/routes/HomeErrorElement.tsx
- #327 
에러 페이지 구현.
위 페이지는 기본값인데 각 텍스트는 다음과 같이 상태로 반영 가능
```tsx
<Navigate
to="/error"
state={{
title: 'ERROR',
summary: '알 수 없는 에러가 발생했습니다.',
fallbacks: [{ name: '홈으로 되돌아가기', url: '/' }],
}}
/>;
// 또는
const fallbacks = [{ name: '홈으로 되돌아가기', url: '/' }];
<Error
title="ERROR"  
summary="알 수 없는 에러가 발생했습니다." 
fallbacks={fallbacks}  
/>
```
- 웬만하면 그냥 기본값 사용하기.
- 채팅 수정 PR 커밋이 반영되어 있기 때문에, 실제로는 커밋 5개밖에 없습니다.
=> [CLIENT] 에러 페이지

server/apps/api/src/channel/channel.controller.ts, server/apps/api/src/channel/channel.service.ts, server/apps/api/src/chat-list/chat-list.service.ts, server/apps/api/src/community/community.module.ts, server/apps/api/src/community/community.service.ts, server/dao/schemas/chat.schema.ts, server/utils/def.ts
- #334
사용자는 다른 커뮤니티, 채널에 안읽은 메세지 여부를 알 수 있다.
- 자신이 속한 커뮤니티, 채널 정보 가져올 때 채널에 안읽은 채팅 존재 여부 확인
- 채널 생성 예외처리 추가
- 안읽은 메세지 없을 경우 응답으로 -1을 보냄
- 채널 생성 시 마지막 방문시간 업데이트
>**커뮤니티 안읽은 채팅 여부 업데이트**
1. 커뮤니티 정보 가져옴 -> 채널에 안읽은 메세지 없음
**채널에 메세지 생성**
2. 커뮤니티 정보 가져옴 -> 채널에 안읽은 메세지 있음
**채널 마지막 방문 시간 업데이트**
3. 커뮤니티 정보 가져옴 -> 채널에 안읽은 메세지 없음
=> [Server/Feature] 커뮤니티에 안읽은 채팅 있는지 확인하는 로직

server/apps/api/src/chat-list/chat-list.controller.ts, server/apps/api/src/chat-list/chat-list.service.ts, server/apps/api/src/chat-list/dto/index.ts, server/apps/api/src/chat-list/dto/modify-message.dto.ts
- #341 
채널 사용자는 자신의 채팅을 수정할 수 있다.
```tsx
requestUserId : mongoId, notEmpty
channel_id: mongoId, notEmpty
chat_id: mongoId, notEmpty
content: string, notEmpty
```
- Patch `api/channel/:channel_id/chats/:chat_id`
- chat_id에 해당하는 메세지를 찾음
- requestUserId와 senderId가 일치하는지 검증
- chat 수정
- 응답 생성
```
{
"type": "TEXT",
"content": "hi",
"channelId": "6394cd01d1a615bf564d9e4c",
"senderId": "6394cc8fd1a615bf564d7e75",
"chatId": 51,
"communityId" : "",
"createdAt": Date(),
"updatedAt": Date(),
}
```
=> [Server/chat] 채팅 수정 기능 구현

client/src/components/GnbItemContainer/index.tsx
- #346
Gnb아이템에 마우스 오버시, 툴팁이 뜨지 않고 React Portal 에러가 발생하는 버그 fix
=> [CLIENT] Tooltip 오류 수정

server/apps/api/src/community/community.service.ts, server/apps/api/src/community/helper/sortedByCreateTime.ts
- #335 
- 정렬 시간 측정 시 비동기로 DB조회 후 sort 하는 것이 빠름
- [정리 notion link](https://grand-beanie-e57.notion.site/d1c6379e5d9949cba574d652ae5f7002)
=> fix: get communities 시 커뮤니티 및 채널 정렬

server/apps/api/src/channel/channel.service.ts, server/apps/api/src/chat-list/chat-list.service.ts
- 채널 관리자가 채널에 유저가 2명 이상 존재하는데 나갈 수 있는 이슈 해결
- `findOne{channel_id: channel_id}` -> `findOne{_id: channel_id}`
- delete하는 부분 동기처리
- 채팅 응답 수정
- `chatId` -> `id`
=> [Server/channel] 채널 버그 해결, 채팅 응답 수정

server/apps/api/src/chat-list/chat-list.controller.ts, server/apps/api/src/chat-list/chat-list.service.ts, server/apps/api/src/chat-list/dto/delete-message.dto.ts, server/dao/repository/chat-list.respository.ts
- #341  
- #357 
채널 사용자는 자신의 채팅을 삭제할 수 있다.
- 채팅 받아올 때 삭제된거 제외하고 받도록 수정
- 채팅 수정, 삭제를 위한 쿼리 작성
- 채팅 수정시 chatList 전부 교체하는 방식 -> 일부만 수정하도록 코드 리팩토링
- 채팅 삭제 기능 구현
https://user-images.githubusercontent.com/72093196/206984891-951bf4da-e923-4f8c-af62-bb1fcf37ee99.mov
>**채팅 삭제**
```
requestUserId: MongoId, NotEmpty
channelId: MongoId, NotEmpty
chatId: NotEmpty
```
- DELETE `api/channel/:channel_id/chats/:chat_id`
- 채널이 존재하는지 확인
- requestUserId와 senderId가 일치하는지 검증
- deletedAt 추가
- 응답
```
"id": 51,
"type": "TEXT",
"content": "hi",
"createdAt": Date(),
"updatedAt": Date(),
"deletedAt": Date(),
"senderId": "6394cc8fd1a615bf564d7e75",
"communityId" : "",
"channelId": "6394cd01d1a615bf564d9e4c",
```
=> [Server/chat] 채팅 수정 리팩토링 및 채팅 삭제 기능 추가

client/src/apis/chat.ts, client/src/components/ChatList/index.tsx, client/src/constants/endPoint.ts, client/src/constants/regex.ts, client/src/hooks/chat.ts, client/src/mocks/handlers/Chat.js, client/src/pages/Channel/index.tsx, client/src/queryClient.ts, client/src/queryKeyCreator.ts, client/src/sockets/ClientIO.ts
- #315 
- 채널 페이지 내에서 안 읽은 메시지를 표시해준다.
- 채널 페이지 첫 입장 시 스크롤 바로 밑으로 안 내려가있는 경우 divider가 제대로 렌더링 안 되는 경우가 있음
=> [CLIENT] 안 읽은 메시지 채널 페이지 내에 렌더링

client/src/components/ChannelCard/index.tsx, client/src/components/ChannelName/index.tsx, client/src/components/ChatForm/index.tsx, client/src/layouts/ChannelInfoLayer/index.tsx, client/src/layouts/SocketLayer/index.tsx, client/src/mocks/handlers/Channel.js, client/src/pages/Channel/index.tsx, client/src/pages/Community/index.tsx, client/tailwind.config.js
- #375 
채널 정보 페이지 (커뮤니티 입장시 보이는 페이지)
=> [CLIENT] 채널 정보 페이지

client/src/components/ChatItem/index.tsx
재전송, 지우기 버튼의 disabled 상태 css적용 (기존에는 재전송시 변화가 없었음)
=> [CLIENT] 재전송, 지우기 버튼 disabled 스타일

client/src/components/ChatList/index.tsx, client/src/hooks/chat.ts, client/src/pages/Channel/index.tsx
- #369 
1. A 채널 페이지를 본다. 채널에 입장했으므로 unreadChatId 쿼리는 -1이 된다.
2. 다른 채널 페이지로 간다. A 채널 페이지에 대한 unreadChatId 쿼리는 inactive가 되며 캐시에 -1이 저장된다.
3. A 채널 페이지에 새로운 메시지가 들어오고 사용자는 A 채널 페이지로 간다. 이때 캐시에는 -1이 저장되어있으므로 우선은 해당 값이 ref에 들어간다. 
4. unreadChatId를 `n`으로 fetch해 온 후 캐시를 업데이트하나 ref.current는 변경되지 않으므로 `n`에 해당하는 `<ChatItem />`위에 new divider가 붙지 않는다.
1. unreadChatId 쿼리의 cacheTime을 0으로 주어 채널 페이지를 벗어나면 = 즉 unreadChatId 쿼리가 inactive된 후 지워지도록 한다.
2. 따라서 채널 페이지에 접속할 때마다 새로운 unreadChatId를 fetch해오도록 한다.
6. 채널 페이지에서 unreadChatId를 fetch해와 -1이 아니면 위에 새로운 메시지가 있다고 표시한다.
7. 채널 페이지가 이 unreadChatId를 ChatList에 내려주어 ref에 해당 id를 저장하도록 한다.
1. 채널 페이지 입장시 스크롤바가 최하단으로 내려가지 않는 문제
2. 새로운 메시지가 있으나 unreadChatId가 -1로 오는 문제
=> [CLIENT] 안 읽은 메시지 버그 수정

server/apps/api/src/community/community.service.ts
문제 : 사용자의 안읽은 채팅 존재 여부를 확인할 수 없는 이슈
원인 : #332 PR에서 코드를 잘 못 수정해서 비교하는 값이 null이 되었음 (편의상 JSON으로 처리한 것을 Map으로 바꾸면서 에러 발생)
해결 : null이 되는 이유를 찾고 코드 수정
=> [Server/community] 안읽은 채팅 존재 여부 확인 못하는 이슈  해결

client/src/App.tsx, client/src/constants/user.ts, client/src/hooks/combine.ts, client/src/hooks/community.ts, client/src/pages/Home/index.tsx
- 일정 간격으로 `communities` 불러오는데, 채널 입장과 퇴장시에만 `lastRead`를 업데이트하기 때문에, 채널에 머무르고 있을 때는 `lastRead`보다 그 사이에 전송된 채팅들의 `createdAt`이 앞서나가서, `communities`를 불러올 때, 보고있는 채널에도 new message가 표시되는 문제
- 일정 간격으로 `communities`불러오기 전에 `lastRead`업데이트 한 뒤에 불러오는 이펙트함수 추가
- 더 이상 내가 입장한 채널에서는 new 메세지가 보이지 않습니다. (new 정보를 불러오기 전에, 채널에 입장해있다면 무조건 lastRead를 업데이트하기 때문에)
=> [CLIENT] 안읽은메세지 버그 수정

client/config/webpack.analysis.ts, client/config/webpack.prod.ts, client/package.json, client/src/App.tsx, yarn.lock
페이지 단위 코드 스플리팅, 번들링 devtools 변경
- `dev`모드:  (번들은 `webpack.prod.ts`로 하는데, devtools를 `inline-source-map` 사용)
- `prod`모드 : (devtools를 `cheap-module-source-map`사용)
`dev`모드의 스플리팅 전
`dev`모드의 스플리팅 후
`prod`모드의 스플리팅 전
`prod`모드의 스플리팅 후 
스플리팅은 페이지 단위로 했습니다.
=> [CLIENT] 페이지 단위 코드 스플리팅, 번들링 devtools 변경

.gitattributes, server/.gitattributes
git attributes 파일 최 상위로 이동해야 languages 설정이 작동하여 변경했습니다.
=> [Hotfix] git attributes 파일 최 상위로 이동

server/apps/api/src/chat-list/chat-list.service.ts
- #415 
안 읽은 채팅이 있음에도 채팅 위치가 받아와지지 않는 이슈 해결
안 읽은 채팅을 찾는 로직을 수정하였습니다.
>**테스트 환경**
POST MAN을 사용
```tsx
pm.test("안 읽은 위치", () => {
pm.expect(pm.response.json().result.unreadChatId).equal(215);   // 215는 고정된 안 읽은 채팅 위치
})
```
채널 마지막 방문 시간을 업데이트 하지 않아 채널의 안 읽은 채팅 위치는 215로 고정되어야 함.
`채팅 저장 -> 안 읽은 위치가 215인지 확인` 과정을 100번 반복함
>**수정 전**
>**수정 후**
```tsx
getUnreadChatId(unreadChatList, lastRead) {
let L = 0;
let R = unreadChatList.length - 1;
let M;
while (L <= R) {
M = Math.floor((L + R) / 2);
if (new Date(unreadChatList[M].createdAt) < lastRead) {
L = M + 1;
} else {
R = M - 1;
}
}
if (new Date(unreadChatList[M].createdAt) < lastRead) {
return NOT_EXIST_UNREAD_CHAT;
}
return unreadChatList[M].id;
}
```
>**버그가 발생하는 예시**
- 0 1 2 3 4 5 6 7 8 총 9개의 채팅이 있을 경우
- 마지막으로 채널에 접속한 시간은 채팅5와 채팅6 사이 시간
- 기대하는 값 …
=> [Server/chat] 안 읽은 채팅 이슈 해결

.github/workflows/server.yml, server/__mock__/user.mock.ts, server/apps/api/src/chat-list/chat-list.service.ts, server/apps/api/src/community/community.service.ts, server/apps/api/src/user/dto/follower.dto.ts, server/apps/api/src/user/dto/get-users.dto.ts, server/apps/api/src/user/dto/modify-user.dto.ts, server/apps/api/src/user/helper/checkRelation.ts, server/apps/api/src/user/user.controller.ts, server/apps/api/src/user/user.service.ts, server/apps/api/src/user/users.controller.ts, server/custom/interceptor/api.interceptor.ts, server/dao/repository/chat-list.respository.ts
- #392 
- 공간 지역성을 고려한 채팅 저장내용 caching
`@Get /api/channels/:channel_id/chat`
prev, next curser를 전달하며 해당 curser에 대한 내용 사전 저장 (유효기간 5분)
[Minor 수정]
- 자신 follow 불가능하도록 수정
- user dto refactoring
- Merge slack bot 중단
18ms -> 8ms 단축
[ 캐싱 전 ]
[ 캐싱 후 ]
=> [Server/Feature] 이전 Chats 사전 Caching

client/src/hooks/useIntersectionObservable.ts, client/src/pages/Channel/index.tsx
- #423 
사용자가 스크롤을 위로 올리면 이전 채팅을 불러오는 API 요청을 중복하여 두 번 보냄
=> [CLIENT] 이전 채팅 불러오는 API 요청이 두 번 발생하는 이슈 해결
